// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/test/csrf/form/_middleware.ts";
import * as $5 from "./routes/test/csrf/form/invalid.tsx";
import * as $6 from "./routes/test/csrf/form/valid.tsx";
import * as $7 from "./routes/test/csrf/result/_middleware.ts";
import * as $8 from "./routes/test/csrf/result/index.tsx";
import * as $9 from "./routes/test/supabase-connection/[request_text].tsx";
import * as $10 from "./routes/test/supabase-connection/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/api/joke.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/test/csrf/form/_middleware.ts": $4,
    "./routes/test/csrf/form/invalid.tsx": $5,
    "./routes/test/csrf/form/valid.tsx": $6,
    "./routes/test/csrf/result/_middleware.ts": $7,
    "./routes/test/csrf/result/index.tsx": $8,
    "./routes/test/supabase-connection/[request_text].tsx": $9,
    "./routes/test/supabase-connection/index.tsx": $10,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
